# Compiling the TypeScript to JavaScript
build:
	npm run build

# Watch for TypeScript file changes and recompile
watch:
	npm run watch

# Serve the application with automatic restarts
serve:
	npm run serve

# Run both watch and serve commands concurrently for seamless development
dev:
	npm run dev

drizzle-push:
	npm run drizzle-push

drizzle-pull:
	npm run drizzle-pull

drizzle-migration:
	npm run drizzle-migration